### ISSUE TITLE
TypeError: got unexpected keyword argument(s) 'use_cudnn', 'bias'

### ISSUE THREAD

**Issue by josedolz** [musyoku/wasserstein-gan#3]
Hi,

I am trying to reproduce the examples of the animefaces and I get this error:

File "/home/josed/Documents/Code/virtual-environments/Chainer2.7/chainer27/local/lib/python2.7/site-packages/chainer/utils/argument.py", line 12, in parse_kwargs
    raise TypeError('got unexpected keyword argument(s) %s' % args)
TypeError: got unexpected keyword argument(s) 'use_cudnn', 'bias'

I am running on Ubuntu 16.04, python 2.7 and Chainer 2.0.0.

Thanks

**Comment by musyoku** [comment]
Sorry for late reply. Fixed now.
Seems that `use_cudnn` option is removed in Chainer v2.

**Comment by josedolz** [comment]
Yep, it seems to work now.

Thanks!!
